name: mutatex

channels:
  - conda-forge
  - defaults

dependencies:
  - biopython=1.81
  - matplotlib=3.8.4
  - pip=24.0
  - python=3.9.7
  - numpy>=1.17.3,<1.25.0
  - scipy=1.8.1
  - six=1.16.0
  - openpyxl=3.1.4
  - pyyaml=6.0.1
  - adjustText>=0.8
  - wheel=0.43.0
