name: stabddg
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.6.0
    - tqdm==4.67.1
    - wandb==0.20.1
    - scipy==1.15.3
    - pandas==2.3.0
    - biopython==1.85
    - scikit-learn==1.7.0
